name: Deploy to Amazon S3

on:
  pull_request:
    branches:
      - 'master'


jobs:
  deploy:
    name: PR Deploy to S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Install npm deps
      run: |
        npm install

    - name: Build the static site
      run: |
        npm run app:build

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync --delete ./build s3://ol-kit/branch/${GITHUB_HEAD_REF}
